[package]
name = "arcanum"
authors = ["Dídac Domenech <didac@domenech.dev>"]
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
dotenvy = "0.15.7"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.21"
askama = "0.15.1"
log = "0.4"
env_logger = "0.11.8"
markdown = "1.0.0"
gray_matter = "0.3.2"
pulldown-cmark = "0.13.0"
actix-files = "0.6.9"
serde_json = "1.0"

# Monitoring
prometheus = "0.14.0"
actix-web-prom = "0.10.0"

# Git Repository synchronization
git2 = "0.20.3"
hmac = "0.12.1"
sha2 = "0.10.9"
hex = "0.4.3"
